<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCarParts" project="project3" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.training.test.TestCarParts" time="2.813">
    <testcase name="test" classname="com.training.test.TestCarParts" time="2.813">
      <error>org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [INSERT into tbl_carparts VALUES(?,?,?)]; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: TBL_CARPARTS&#13;
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:91)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)&#13;
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:660)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:909)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:970)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:980)&#13;
	at com.training.dao.CarPartsInventoryImpl.addNewPart(CarPartsInventoryImpl.java:23)&#13;
	at com.training.test.TestCarParts.test(TestCarParts.java:23)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: TBL_CARPARTS&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.JDBCPreparedStatement.&lt;init&gt;(Unknown Source)&#13;
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)&#13;
	at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1557)&#13;
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638)&#13;
	... 28 more&#13;
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: TBL_CARPARTS&#13;
	at org.hsqldb.error.Error.error(Unknown Source)&#13;
	at org.hsqldb.error.Error.error(Unknown Source)&#13;
	at org.hsqldb.SchemaManager.getTable(Unknown Source)&#13;
	at org.hsqldb.ParserDQL.readTableName(Unknown Source)&#13;
	at org.hsqldb.ParserDQL.readSimpleRangeVariable(Unknown Source)&#13;
	at org.hsqldb.ParserDML.compileInsertStatement(Unknown Source)&#13;
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)&#13;
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)&#13;
	at org.hsqldb.Session.compileStatement(Unknown Source)&#13;
	at org.hsqldb.StatementManager.compile(Unknown Source)&#13;
	at org.hsqldb.Session.execute(Unknown Source)&#13;
	... 32 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
